server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  database: 'cryptomonitoringprod'

admin:
  email: 'test@gmail.com'
  password: 'IWannaFly'

jwt:
  expiresIn: 86400

email:
  service: 'gmail'
  user: 'sorenharfagri@gmail.com'
  receiver: 'QVing612@gmail.com'
  password: 'NMzYMOZR3qw1'
