db:
  host: 'localhost'
  username: 'postgres'
  password: 'admin'
  database: 'cryptomonitoring'
  synchronize: true

jwt:
  secret: 'topSecret51'

admin:
  email: 'test@gmail.com'
  password: 'IWannaFly'
