admin:
  email: 'test@gmail.com'
  password: 'IWannaFly'

jwt:
  secret: '655afd70c47be89de9e8295a1982e96b5804419'
  expiresIn: 86400

server:
  port: 80

db:
  host: 'localhost'
  username: 'admin'
  password: '1234'
  synchronize: true

email:
  service: 'gmail'
  user: 'monitoringcrypto@gmail.com'
  receiver: 'cscrypto29@gmail.com'
<<<<<<< HEAD
  password: '123123Opus'
=======
  password: '123123Opus'
>>>>>>> m2-deploy
